# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 5, 1, 44, 47, 22385), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
