# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200605_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 5, 3, 3, 6, 296245), verbose_name='Опубликована'),
        ),
    ]
