# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200605_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 5, 3, 14, 43, 906087), verbose_name='Опубликована'),
        ),
    ]
